spring.application.name=nutrition-api

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

application.security.jwt.secret-key=${JWT_SECRET}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.main.allow-bean-definition-overriding=true

app.cors.allowed-origins=${CORS_ORIGINS:http://localhost:3000}

